api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
        options: modern@file
    http3: {}

providers:
  file:
    directory: /config
    watch: true
  docker:
    endpoint: "tcp://socket-proxy:2375"
    exposedByDefault: false

# Let's Encrypt configuration
certificatesResolvers:
  letsencrypt:
    acme:
      # See .env.traefik.example for more info and stg/prod values
      # email: <TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL>
      # caServer: <TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_CASERVER>
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

# https://doc.traefik.io/traefik/routing/services/#insecureskipverify
serversTransport:
  insecureSkipVerify: true

# Logging
log:
  level: INFO
  format: json

accessLog:
  format: json
  fields:
    headers:
      defaultMode: drop

