#!/usr/bin/env bash
#
# Print a recommended compose override with mem_limit values for every
# service, derived from the host's CPU + RAM as the docker daemon sees it.
# Header goes to stderr so stdout is pure YAML and capturable.
#
# Usage: scripts/host-resources.sh           (stdout: YAML; stderr: header)
#        scripts/host-resources.sh > compose.resource-limits.yml
#
# Cross-platform: reads `docker info` rather than /proc/meminfo + nproc, so
# this works on Linux deploy targets, macOS Docker Desktop, and Docker
# Desktop on Windows / WSL2. On Desktop the values reflect the VM's
# allocation rather than the physical host — which is correct, since the
# containers can't escape the VM anyway.
#
# Assumes a DEDICATED host. Operators on shared hosts should hand-edit the
# output before enabling it in COMPOSE_FILE.

set -euo pipefail

TOTAL_MEM_BYTES=$(docker info --format '{{.MemTotal}}' 2>/dev/null || true)
TOTAL_CPU=$(docker info --format '{{.NCPU}}' 2>/dev/null || true)
if [ -z "$TOTAL_MEM_BYTES" ] || [ "$TOTAL_MEM_BYTES" = "0" ]; then
  echo "Error: 'docker info' did not return a host memory total — is the docker daemon reachable?" >&2
  exit 1
fi
TOTAL_MEM_MB=$((TOTAL_MEM_BYTES / 1024 / 1024))

# Fixed-size service ceilings (bounded workloads).
OS_RESERVE_MB=512
NGINX_API_MEM=128
REDIS_MEM=384       # > --maxmemory 256mb so the kernel OOM is the hard stop
TRAEFIK_MEM=256
SOCKET_PROXY_MEM=64

FIXED_TOTAL=$((OS_RESERVE_MB + NGINX_API_MEM + REDIS_MEM + TRAEFIK_MEM + SOCKET_PROXY_MEM))
DYNAMIC_MEM_MB=$((TOTAL_MEM_MB - FIXED_TOTAL))

if [ "$DYNAMIC_MEM_MB" -lt 1024 ]; then
  echo "Error: host has ${TOTAL_MEM_MB} MiB RAM; not enough headroom after fixed-size service ceilings (${FIXED_TOTAL} MiB)." >&2
  echo "       Need at least 1 GiB usable for the os2display + mariadb dynamic split (so >= 2.3 GiB total host RAM)." >&2
  exit 1
fi

# Heuristic split (50% / 30% leaves ~20% slack).
OS2DISPLAY_MEM=$((DYNAMIC_MEM_MB * 50 / 100))
MARIADB_MEM=$((DYNAMIC_MEM_MB * 30 / 100))

# Header to stderr.
{
  echo "Host: ${TOTAL_CPU} CPUs, ${TOTAL_MEM_MB} MiB RAM"
  echo "Fixed-size ceilings (small services + OS):"
  echo "  OS reserve:    ${OS_RESERVE_MB} MiB"
  echo "  nginx-api:     ${NGINX_API_MEM} MiB"
  echo "  redis:         ${REDIS_MEM} MiB  (above --maxmemory 256mb in-process limit)"
  echo "  traefik:       ${TRAEFIK_MEM} MiB"
  echo "  socket-proxy:  ${SOCKET_PROXY_MEM} MiB"
  echo "Dynamic allocation (50% / 30%, ~20% slack):"
  echo "  os2display:    ${OS2DISPLAY_MEM} MiB"
  echo "  mariadb:       ${MARIADB_MEM} MiB"
  echo
  echo "Capture this output into compose.resource-limits.yml and enable in .env:"
  echo "  COMPOSE_FILE=docker-compose.yml:compose.resource-limits.yml"
} >&2

cat <<EOF
# Compose override for resource limits — generated by \`task host:resources\`.
# Assumes a dedicated host; revise mem_limit values for shared hosts.
services:
  os2display:
    mem_limit: ${OS2DISPLAY_MEM}m
  nginx-api:
    mem_limit: ${NGINX_API_MEM}m
  redis:
    mem_limit: ${REDIS_MEM}m
  mariadb:
    mem_limit: ${MARIADB_MEM}m
  traefik:
    mem_limit: ${TRAEFIK_MEM}m
  socket-proxy:
    mem_limit: ${SOCKET_PROXY_MEM}m
EOF
